### PR TITLE
ATO-682: Remove orch function name env variables

### PR DESCRIPTION
**Pull request by CarlyG55**
## What

Refactor to remove the need for function name env variables. Created a new local for secure pipelines equivalent environment
## How to review

Make sure the old names match up with new names

### CODE REVIEW

**Comment by isaac-GDS** [comment]
Nice ! Much better then repeating it in the tf.vars file. Good stuff.

**Comment by isaac-GDS** [comment]
Saw that for the TrustmarkFunction we never had specified function name will that cause problems ?

**Comment by CarlyG55** [comment]
@isaac-GDS I also noticed that 😆 I'm assuming we never actually tested it - I don't think adding the name will cause issues

**Comment by isaac-GDS** [comment]
Think Cloudformation is smart enough to delete the old lambda and recreate with the updated name. So happy enough :)

**Review by isaac-GDS — APPROVED** [review]

**Comment by CarlyG55** [comment]
@isaac-GDS this won't change cloudformation, these changes are in terraform, and when I did a plan I couldn't see any changes as the string used remains the same

**Comment by isaac-GDS** [comment]
Ah yes of course - silly me. All fine then :)

**Pull request merged**
